In [1]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
plt.style.use('seaborn-white')
%matplotlib inline
from sklearn.metrics import *
from sklearn import metrics
import xgboost as xgb
from sklearn.model_selection import  train_test_split

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\dask\dataframe\utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:

df=pd.read_csv('../Data/test_csv_main_upsampled.csv')
df

,age,bmi,alcohol,cannabis,contacts_count,covid19_symptoms,covid19_contact,asthma,kidney_disease,liver_disease,...,heart_disease,lung_disease,diabetes,hiv_positive,hypertension,other_chronic,health_worker,sex,smoking,covid19_positive
0,4,22.614941,2,2.691281,20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
1,5,27.500000,0,2.691281,20,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,3,34.200000,-1,2.691281,21,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,0
3,9,31.300000,0,2.691281,1,0,0,0,0,0,...,1,0,0,0,0,0,0,1,1,1
4,4,36.730399,3,2.691281,7,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20298,6,28.300000,10,20.000000,3,0,1,0,0,0,...,0,0,0,0,1,0,1,1,0,0
20299,3,22.142372,4,25.820465,20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20300,2,48.600000,-1,2.691281,10,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
20301,6,27.100000,-1,-1.000000,21,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
20302,2,19.800000,-1,2.691281,21,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [3]:
df1=pd.read_csv('../Data/train_csv_main_upsampled.csv')
df1

,age,bmi,alcohol,cannabis,contacts_count,covid19_symptoms,covid19_contact,asthma,kidney_disease,liver_disease,...,heart_disease,lung_disease,diabetes,hiv_positive,hypertension,other_chronic,health_worker,sex,smoking,covid19_positive
0,3,29.000000,1,0.000000,1,1,0,0,0,0,...,0,0,0,0,0,0,0,1,3,0
1,5,24.072751,7,2.691281,6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,1
2,5,22.300000,13,0.000000,21,1,0,1,0,0,...,0,0,0,0,0,0,0,0,7,0
3,5,34.200000,1,2.691281,18,0,1,1,0,0,...,0,0,0,0,1,0,1,0,0,0
4,4,39.600000,0,0.000000,8,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60904,5,29.600000,2,-1.000000,5,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60905,6,20.492990,1,2.691281,20,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
60906,8,31.554536,-1,2.691281,20,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,1
60907,3,22.300000,-1,2.691281,10,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
60908,4,22.800000,0,-1.000000,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X_train=df1.drop(columns='covid19_positive')
y_train=df1['covid19_positive']
X_test=df.drop(columns='covid19_positive')
y_test=df['covid19_positive']

In [5]:
import pickle
filename='../Trained_models/xgb_without_HHO.pkl'

In [7]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)

In [8]:
accuracy_score(y_test,result)

0.831551987391026

In [9]:
cohen_kappa_score(y_test,result)

0.6631097766141285

In [17]:
print('classification report for XGB without HHO:')
print('', classification_report(y_test,result))

classification report for XGB without HHO:
               precision    recall  f1-score   support

           0       0.84      0.83      0.83     10167
           1       0.83      0.84      0.83     10136

    accuracy                           0.83     20303
   macro avg       0.83      0.83      0.83     20303
weighted avg       0.83      0.83      0.83     20303